<?php

namespace conerd\humhub\modules\relationships;

use conerd\humhub\modules\relationships\migration\Enable;
use conerd\humhub\modules\relationships\migration\Uninstall;
use Yii;
use yii\helpers\Url;
use humhub\modules\content\components\ContentContainerActiveRecord;
use humhub\modules\user\models\User;

class Module extends \humhub\modules\content\components\ContentContainerModule
{
    /**
    * @inheritdoc
    */
    public function getContentContainerTypes()
    {
        return [
            User::class
        ];
    }

    /**
    * @inheritdoc
    */
    public function getConfigUrl()
    {
        return Url::to(['/relationships/admin']);
    }

    public function enable()
    {
        $enable = new Enable();
        $enable->safeUp();
        return parent::enable(); // TODO: Change the autogenerated stub
    }

    /**
    * @inheritdoc
    */
    public function disable()
    {
        $disable = new Uninstall();
        $disable->up();
        // Cleanup all module data, don't remove the parent::disable()!!!
        parent::disable();
    }

    /**
    * @inheritdoc
    */
    public function disableContentContainer(ContentContainerActiveRecord $container)
    {
        // Clean up space related data, don't remove the parent::disable()!!!
        parent::disable();
    }

    /**
    * @inheritdoc
    */
    public function getContentContainerName(ContentContainerActiveRecord $container)
    {
        return Yii::t('RelationshipsModule.base', 'Relationships');
    }

    /**
    * @inheritdoc
    */
    public function getContentContainerDescription(ContentContainerActiveRecord $container)
    {
        return Yii::t('RelationshipsModule.base', 'Create relationships between users.');
    }

    public function getPath(){
        return "protected/modules/relationships";
    }
}
